package ui;

import courses.Course;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import services.CourseService;

public class AdminDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());
    private CourseService courseservice;

    /**
     * Creates new form admin
     */
    public AdminDashboard(CourseService courseservice) {
    this.courseservice = courseservice;
    initComponents();       // create components first
    setTitle("Admin Dashboard");
    loadPendingCourses(); 
    }

    private void loadPendingCourses() {
        // Get only pending courses from your service
        ArrayList<Course> pendingCourses = courseservice.getPendingCourses();
        // Prepare the table model
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) courseTable.getModel();
        // Clear existing rows
        model.setRowCount(0);
        // Add each pending course to the table
        for (Course course : pendingCourses) {
            model.addRow(new Object[]{
                course.getCourseID(),
                course.getTitle(),
                course.getDescription(),
                course.getInstructorID()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        acceptCourse = new javax.swing.JButton();
        declineCourse = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        courseTable.setBackground(new java.awt.Color(204, 204, 204));
        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Title", "Course Descripton", "Instructor ID"
            }
        ));
        jScrollPane1.setViewportView(courseTable);

        acceptCourse.setText("Accept Course");
        acceptCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptCourseActionPerformed(evt);
            }
        });

        declineCourse.setText("Decline Course");
        declineCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineCourseActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acceptCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(declineCourse)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptCourse)
                    .addComponent(declineCourse))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptCourseActionPerformed
    int selectedRow = courseTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.", "No selection", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String courseId = courseTable.getValueAt(selectedRow, 0).toString();

        try {
            courseservice.approveCourse(courseId);
        } catch (IOException ex) {
            System.getLogger(AdminDashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    JOptionPane.showMessageDialog(this, "Course " + courseId + " approved.", "Success", JOptionPane.INFORMATION_MESSAGE);
    loadPendingCourses();
    }//GEN-LAST:event_acceptCourseActionPerformed

    private void declineCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineCourseActionPerformed
        int selectedRow = courseTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.", "No selection", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String courseId = courseTable.getValueAt(selectedRow, 0).toString();
    String instructorID = courseTable.getValueAt(selectedRow, 3).toString();

        try {
            courseservice.rejectCourse(courseId, instructorID);
        } catch (IOException ex) {
            System.getLogger(AdminDashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    JOptionPane.showMessageDialog(this, "Course " + courseId + " rejected.", "Success", JOptionPane.INFORMATION_MESSAGE);
    loadPendingCourses();
    }//GEN-LAST:event_declineCourseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            Login lg = new Login();
            lg.setVisible(true);

        } catch (IOException e) {
            System.getLogger(InstructorDashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptCourse;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton declineCourse;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
