package ui;

import courses.Course;
import courses.Lesson;
import misc.Validations;
import services.UserService;
import services.CourseService;
import java.io.IOException;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import javax.swing.JOptionPane;
import users.Student;

public class InstructorDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InstructorDashboard.class.getName());
    private CourseService cs;

    private String instructorID;

    public InstructorDashboard(String instructorID) {
        this.instructorID = instructorID;
        try {
            cs = new CourseService();
        } catch (IOException e) {

            logger.log(java.util.logging.Level.SEVERE, null, e);
        }

        initComponents();
        setLocationRelativeTo(null);
        setSize(422, 370); 
        setTitle("Instructor Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addLesson = new javax.swing.JButton();
        deleteLesson = new javax.swing.JButton();
        editLesson = new javax.swing.JButton();
        enrolledStudents = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addCourse = new javax.swing.JButton();
        deleteCourse = new javax.swing.JButton();
        editCourse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        addLesson.setText("Add Lesson");
        addLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonActionPerformed(evt);
            }
        });

        deleteLesson.setText("Delete Lesson");
        deleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLessonActionPerformed(evt);
            }
        });

        editLesson.setText("Edit Lesson");
        editLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLessonActionPerformed(evt);
            }
        });

        enrolledStudents.setText("Enrolled Students");
        enrolledStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolledStudentsActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addCourse.setText("Add Course");
        addCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseActionPerformed(evt);
            }
        });

        deleteCourse.setText("Delete Course");
        deleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseActionPerformed(evt);
            }
        });

        editCourse.setText("Edit Course");
        editCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCourseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("manage courses");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(enrolledStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLesson)
                    .addComponent(addCourse))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLesson)
                    .addComponent(deleteCourse))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLesson)
                    .addComponent(editCourse))
                .addGap(28, 28, 28)
                .addComponent(enrolledStudents)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLessonActionPerformed
        // TODO add your handling code here:
        try {
            String courseID = JOptionPane.showInputDialog(this, "Course ID:");
            String lessonID = JOptionPane.showInputDialog(this, "Lesson ID:");

            Course course = cs.findCourse(courseID);
            if (course == null) {
                JOptionPane.showMessageDialog(this, "Course not found!");
                return;
            }
            Lesson oldLesson = cs.findLessonInCourse(lessonID, course);
            if (oldLesson == null) {
                JOptionPane.showMessageDialog(this, "Lesson not found!");
                return;
            }
            String newTitle = JOptionPane.showInputDialog(this, "New Title:");
            String newContent = JOptionPane.showInputDialog(this, "New Content:");

            Lesson edited = new Lesson(lessonID, newTitle, newContent, courseID);

            cs.editLesson(edited, courseID, this.instructorID);

            JOptionPane.showMessageDialog(this, "Lesson updated successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_editLessonActionPerformed

    private void addLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonActionPerformed
        // TODO add your handling code here:
        try {
            String courseID = JOptionPane.showInputDialog(this, "Course ID:");
            String title = JOptionPane.showInputDialog(this, "Lesson Title:");
            String content = JOptionPane.showInputDialog(this, "Lesson Content:");

            cs.addLesson(title, content, courseID, this.instructorID);

            JOptionPane.showMessageDialog(this, "Lesson added successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_addLessonActionPerformed

    private void addCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseActionPerformed
        // TODO add your handling code here:
        try {
            String title = javax.swing.JOptionPane.showInputDialog(this, "Course Title:");
            String desc = javax.swing.JOptionPane.showInputDialog(this, "Course Description:");

            cs.createCourse(title, desc, instructorID);
            javax.swing.JOptionPane.showMessageDialog(this, "Course Added Successfully!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_addCourseActionPerformed

    private void deleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseActionPerformed
        // TODO add your handling code here:
        try {
            String courseID = JOptionPane.showInputDialog(this, "Course ID to delete:");

            cs.deleteCourse(courseID, this.instructorID);

            JOptionPane.showMessageDialog(this, "Course deleted successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteCourseActionPerformed

    private void deleteLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLessonActionPerformed
        // TODO add your handling code here:
        try {
            String courseID = JOptionPane.showInputDialog(this, "Course ID:");
            String lessonID = JOptionPane.showInputDialog(this, "Lesson ID:");

            cs.removeLesson(courseID, lessonID, this.instructorID);
            JOptionPane.showMessageDialog(this, "Lesson deleted successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteLessonActionPerformed

    private void editCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCourseActionPerformed
        // TODO add your handling code here:
        try {
            String courseID = JOptionPane.showInputDialog(this, "Course ID to edit:");

            Course oldCourse = cs.findCourse(courseID);
            if (oldCourse == null) {
                JOptionPane.showMessageDialog(this, "Course not found!");
                return;
            }
            String newTitle = JOptionPane.showInputDialog(this, "New Title:");
            String newDescription = JOptionPane.showInputDialog(this, "New Description:");

            Course updated = new Course(
                    oldCourse.getCourseID(),
                    newTitle,
                    newDescription,
                    oldCourse.getInstructorID()
            );
            for (Lesson l : oldCourse.getLessons()) {
                updated.addLesson(l);
            }
            for (Student s : oldCourse.getStudents()) {
                updated.addStudent(s);
            }
            cs.editCourse(oldCourse.getCourseID(), newTitle, newDescription, this.instructorID);

            JOptionPane.showMessageDialog(this, "Course updated successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_editCourseActionPerformed

    private void enrolledStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolledStudentsActionPerformed
        // TODO add your handling code here:
        String courseID = JOptionPane.showInputDialog("Enter Course ID:");

        if (courseID != null && !courseID.trim().isEmpty()) {
            enrolled_students es = new enrolled_students(courseID, cs);
            es.setVisible(true);
        }
    }//GEN-LAST:event_enrolledStudentsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();

        try {
            // TODO add your handling code here:

            Login lg = new Login();
            lg.setVisible(true);
        } catch (IOException ex) {
            System.getLogger(InstructorDashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InstructorDashboard("123").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourse;
    private javax.swing.JButton addLesson;
    private javax.swing.JButton deleteCourse;
    private javax.swing.JButton deleteLesson;
    private javax.swing.JButton editCourse;
    private javax.swing.JButton editLesson;
    private javax.swing.JButton enrolledStudents;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
