/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import courses.Course;
import courses.Lesson;
import java.io.IOException;
import services.CourseService;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import users.User;

/**
 *
 * @author amr
 */
public class StudentDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentDashboard.class.getName());
    private User log;
    /**
     * Creates new form StudentDashboard
     */
    public StudentDashboard(User user) {
        initComponents();
        setTitle("Student Dashboard");
        setSize(720, 550);     
        setLocationRelativeTo(null);
        this.log=user;
        jTextField1.setText(user.getUsername());
        jTextField2.setText(user.getEmail());
        jTextField3.setText(user.getID());
    }
    
     public void loadTable() throws IOException {
        DefaultTableModel m = (DefaultTableModel) All_Courses.getModel();
        m.setRowCount(0);
        CourseService service = new CourseService();
        
        ArrayList<Course> available = service.returnAllCourses();
        for (Course c : available) {
          m.addRow(new Object[]{c.getCourseID(),c.getTitle(),c.getDescription(),c.getInstructorID()});
    }
     }
     
     public void loadEnrolledCourses() throws IOException {
      DefaultTableModel m = (DefaultTableModel) Selected_Courses.getModel();
       m.setRowCount(0);

      CourseService service = new CourseService();
      Set<Course> enrolled = service.enrolledcourses(log.getID());
      
      if(enrolled.isEmpty()){
          return;
      }
      
      for (Course c : enrolled) {
        m.addRow(new Object[]{c.getCourseID(),c.getTitle(),c.getDescription(),c.getInstructorID()});
    }}
     
     private void loadLessonsIntoTable(String courseID) {
    try {
        DefaultTableModel model = (DefaultTableModel) Lessons.getModel();
        model.setRowCount(0);

        CourseService service = new CourseService();
        ArrayList<Lesson> lessons = service.getLessons(courseID);
        Set<String> completed = service.completedLessons(log.getID(),courseID);

        for (Lesson L : lessons) {
            model.addRow(new Object[]{L.getLessonID(), L.getTitle(),completed.contains(L.getLessonID()) ? "Yes" : "No"
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        View_available_courses = new javax.swing.JButton();
        View_enrolled_courses = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        CertificateEarned = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Logout = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        All_Courses = new javax.swing.JTable();
        EnrollCourse = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Selected_Courses = new javax.swing.JTable();
        Viewlesson = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lessons = new javax.swing.JTable();
        MarkCompleted = new javax.swing.JToggleButton();
        ViewContent = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        TakeQuiz = new javax.swing.JToggleButton();
        Back = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        Download_certification = new javax.swing.JToggleButton();
        View_certification = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        certification = new javax.swing.JTable();

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Enroll  Course");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 645, 0);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("welcome ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 710, 90);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        View_available_courses.setBackground(new java.awt.Color(153, 153, 153));
        View_available_courses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_available_courses.setText("View available  courses");
        View_available_courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_available_coursesActionPerformed(evt);
            }
        });

        View_enrolled_courses.setBackground(new java.awt.Color(153, 153, 153));
        View_enrolled_courses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_enrolled_courses.setText("View enrolled  courses");
        View_enrolled_courses.setMinimumSize(new java.awt.Dimension(183, 27));
        View_enrolled_courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_enrolled_coursesActionPerformed(evt);
            }
        });

        Home.setBackground(new java.awt.Color(153, 153, 153));
        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        CertificateEarned.setBackground(new java.awt.Color(153, 153, 153));
        CertificateEarned.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CertificateEarned.setText("Certificate Earned");
        CertificateEarned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CertificateEarnedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(View_available_courses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_enrolled_courses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CertificateEarned, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Home)
                .addGap(60, 60, 60)
                .addComponent(View_available_courses)
                .addGap(59, 59, 59)
                .addComponent(View_enrolled_courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(CertificateEarned)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 90, 200, 430);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        jTextField1.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        jLabel2.setToolTipText("");

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID");

        jTextField3.setEditable(false);

        Logout.setBackground(new java.awt.Color(102, 102, 102));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addComponent(Logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        All_Courses.setBackground(new java.awt.Color(204, 204, 204));
        All_Courses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        All_Courses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseID", "Title", "Description", "InstructorID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        All_Courses.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(All_Courses);
        if (All_Courses.getColumnModel().getColumnCount() > 0) {
            All_Courses.getColumnModel().getColumn(0).setMinWidth(60);
            All_Courses.getColumnModel().getColumn(0).setPreferredWidth(60);
            All_Courses.getColumnModel().getColumn(0).setMaxWidth(60);
            All_Courses.getColumnModel().getColumn(1).setMinWidth(140);
            All_Courses.getColumnModel().getColumn(1).setMaxWidth(140);
            All_Courses.getColumnModel().getColumn(3).setMinWidth(70);
            All_Courses.getColumnModel().getColumn(3).setPreferredWidth(70);
            All_Courses.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        EnrollCourse.setBackground(new java.awt.Color(102, 102, 102));
        EnrollCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EnrollCourse.setText("Enroll Course");
        EnrollCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EnrollCourse)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EnrollCourse)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("tab2", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        Selected_Courses.setBackground(new java.awt.Color(204, 204, 204));
        Selected_Courses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Selected_Courses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseID", "Title", "Description", "InstructorID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Selected_Courses);
        if (Selected_Courses.getColumnModel().getColumnCount() > 0) {
            Selected_Courses.getColumnModel().getColumn(0).setMinWidth(60);
            Selected_Courses.getColumnModel().getColumn(0).setPreferredWidth(60);
            Selected_Courses.getColumnModel().getColumn(0).setMaxWidth(60);
            Selected_Courses.getColumnModel().getColumn(1).setMinWidth(140);
            Selected_Courses.getColumnModel().getColumn(1).setMaxWidth(140);
            Selected_Courses.getColumnModel().getColumn(3).setMinWidth(70);
            Selected_Courses.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        Viewlesson.setBackground(new java.awt.Color(102, 102, 102));
        Viewlesson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Viewlesson.setText("View lesson");
        Viewlesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewlessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Viewlesson)
                .addGap(18, 18, 18))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(Viewlesson)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("tab3", jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        Lessons.setBackground(new java.awt.Color(204, 204, 204));
        Lessons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "LessonID", "Title", "Completed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Lessons);

        MarkCompleted.setBackground(new java.awt.Color(102, 102, 102));
        MarkCompleted.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MarkCompleted.setText("Mark Completed");
        MarkCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkCompletedActionPerformed(evt);
            }
        });

        ViewContent.setBackground(new java.awt.Color(102, 102, 102));
        ViewContent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewContent.setText("View Content");
        ViewContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewContentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ViewContent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MarkCompleted)
                .addGap(17, 17, 17))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarkCompleted)
                    .addComponent(ViewContent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel8);

        TakeQuiz.setBackground(new java.awt.Color(102, 102, 102));
        TakeQuiz.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TakeQuiz.setText("Take Quiz");
        TakeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeQuizActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(102, 102, 102));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(TakeQuiz)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TakeQuiz)
                    .addComponent(Back))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("tab5", jPanel3);

        Download_certification.setBackground(new java.awt.Color(102, 102, 102));
        Download_certification.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Download_certification.setText("Download certification");
        Download_certification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Download_certificationActionPerformed(evt);
            }
        });

        View_certification.setBackground(new java.awt.Color(102, 102, 102));
        View_certification.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_certification.setText("View certification");
        View_certification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_certificationActionPerformed(evt);
            }
        });

        certification.setBackground(new java.awt.Color(204, 204, 204));
        certification.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "certificate ID", "course ID", "issue date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(certification);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(View_certification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Download_certification)
                .addGap(14, 14, 14))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Download_certification)
                    .addComponent(View_certification))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("tab6", jPanel9);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(200, 60, 510, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_available_coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_available_coursesActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
         try {
           loadTable();
        } catch (IOException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_View_available_coursesActionPerformed

    private void View_enrolled_coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_enrolled_coursesActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);  
        try {
          loadEnrolledCourses();  
        } catch (IOException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_View_enrolled_coursesActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_HomeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MarkCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkCompletedActionPerformed
        // TODO add your handling code here:
        int row = Lessons.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a lesson first !");
            return;
        }

        String lessonID = Lessons.getValueAt(row, 0).toString();
        String courseID = Selected_Courses.getValueAt(Selected_Courses.getSelectedRow(), 0).toString();

        try {

            Lessons.setValueAt("Yes", row, 2);

            JOptionPane.showMessageDialog(this, "Lesson marked as completed !");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_MarkCompletedActionPerformed

    private void ViewlessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewlessonActionPerformed
        // TODO add your handling code here:
        int row = Selected_Courses.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course first !");
            return;
        }

        String courseID = Selected_Courses.getValueAt(row, 0).toString();

        loadLessonsIntoTable(courseID);

        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_ViewlessonActionPerformed

    private void EnrollCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollCourseActionPerformed
        // TODO add your handling code here:
     
        int row = All_Courses.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course first !");
            return;
        }

        String courseID = All_Courses.getValueAt(row, 0).toString();
        String studentID = log.getID();

        try {
            CourseService service = new CourseService();
            Set<Course> enrolled = service.enrolledcourses(studentID);

            if (service.studentInCourse(studentID, courseID)) {
                JOptionPane.showMessageDialog(this,"You are already enrolled in this course.");
                return;
            }

            CourseService.enrollStudent(studentID, courseID);
            JOptionPane.showMessageDialog(this, "Enrolled successfully!");

            loadEnrolledCourses();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_EnrollCourseActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new Login().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void ViewContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewContentActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4); 
    }//GEN-LAST:event_ViewContentActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3); 
    }//GEN-LAST:event_BackActionPerformed

    private void TakeQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeQuizActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TakeQuizActionPerformed

    private void CertificateEarnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CertificateEarnedActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5); 
    }//GEN-LAST:event_CertificateEarnedActionPerformed

    private void Download_certificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Download_certificationActionPerformed
        // TODO add your handling code here:
        int row = certification.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select Certificate first !");
            return;
        }
    }//GEN-LAST:event_Download_certificationActionPerformed

    private void View_certificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_certificationActionPerformed
        // TODO add your handling code here:
        int row = certification.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select Certificate first !");
            return;
        }
    }//GEN-LAST:event_View_certificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new StudentDashboard(User user).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable All_Courses;
    private javax.swing.JToggleButton Back;
    private javax.swing.JButton CertificateEarned;
    private javax.swing.JToggleButton Download_certification;
    private javax.swing.JToggleButton EnrollCourse;
    private javax.swing.JButton Home;
    private javax.swing.JTable Lessons;
    private javax.swing.JButton Logout;
    private javax.swing.JToggleButton MarkCompleted;
    private javax.swing.JTable Selected_Courses;
    private javax.swing.JToggleButton TakeQuiz;
    private javax.swing.JToggleButton ViewContent;
    private javax.swing.JButton View_available_courses;
    private javax.swing.JToggleButton View_certification;
    private javax.swing.JButton View_enrolled_courses;
    private javax.swing.JToggleButton Viewlesson;
    private javax.swing.JTable certification;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
